services:
  # Main Web Service
  - type: web
    name: mgnrega-dashboard
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install:all && npm run build:frontend
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_GOV_API_KEY
        value: 579b464db66ec23bdd000001cde4e6f4672b4884773391b3f9d2a01a
      - key: DATA_GOV_BASE_URL
        value: https://api.data.gov.in/resource
      - key: NEXT_PUBLIC_API_URL
        value: https://mgnrega-eirq.onrender.com
      - key: NEXT_PUBLIC_ENABLE_GEOLOCATION
        value: "true"
      - key: JWT_SECRET
        generateValue: true

  # Background Worker (Optional)
  - type: worker
    name: mgnrega-worker
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install:all
    startCommand: npm run worker

databases:
  # PostgreSQL Database
  - name: mgnrega-db
    plan: free
    region: oregon